from pathlib import Path

p=Path('lunea-user-spread-learning-v1.js')
s=p.read_text()

s=s.replace('LUNEA USER SPREAD LEARNING V1.5','LUNEA USER SPREAD LEARNING V1.6',1)

old="""    const all=`${q} ${hint}`;\n    const domain=categoryHint==='INTIMACY'||/(속궁합|성적\\s*(?:궁합|끌림|욕구|리듬|텐션|만족)|신체적\\s*(?:끌림|친밀|궁합)|성관계|섹스|키스|애무|첫\\s*관계|잠자리|19\\+|18\\+)/.test(all)?'intimacy'\n      :/(주식|종목|매수|매도|익절|손절|추매|보유)/.test(all)?'stock'\n      :/(시험|합격|공부|학습|강의|점수)/.test(all)?'study'\n      :/(직장|회사|이직|퇴사|상사|동료|면접|커리어)/.test(all)?'career'\n      :/(돈|금전|재정|지출|수입|부채)/.test(all)?'money'\n      :/(건강|몸|컨디션|피곤|회복|수면)/.test(all)?'wellbeing'\n      :categoryHint==='LOVE'||/(상대|연애|사랑|감정|마음|연락|재회|이별|썸|전남|전여|남친|여친)/.test(all)?'relationship'\n      :'general';\n"""
new="""    const all=`${q} ${hint}`;\n    const relationshipSubject=/(?:\\b[a-z]\\b|그\\s*사람|그녀|그남자|그여자).{0,24}(?:나를|내게|나와|우리)/i.test(q)\n      ||/(?:나를|내게|나와).{0,24}(?:어떻게\\s*(?:생각|보|봤)|감정|마음)/.test(q);\n    const domain=categoryHint==='INTIMACY'||/(속궁합|성적\\s*(?:궁합|끌림|욕구|리듬|텐션|만족)|신체적\\s*(?:끌림|친밀|궁합)|성관계|섹스|키스|애무|첫\\s*관계|잠자리|19\\+|18\\+)/.test(all)?'intimacy'\n      :/(주식|종목|매수|매도|익절|손절|추매|보유)/.test(all)?'stock'\n      :/(시험|합격|공부|학습|강의|점수)/.test(all)?'study'\n      :/(직장|회사|이직|퇴사|상사|동료|면접|커리어)/.test(all)?'career'\n      :/(돈|금전|재정|지출|수입|부채)/.test(all)?'money'\n      :/(건강|몸|컨디션|피곤|회복|수면)/.test(all)?'wellbeing'\n      :categoryHint==='LOVE'||relationshipSubject||/(상대|연애|사랑|감정|마음|연락|재회|이별|썸|전남|전여|남친|여친|관계|답장)/.test(all)?'relationship'\n      :'general';\n"""
if old not in s: raise SystemExit('domain block not found')
s=s.replace(old,new,1)

old="""    const modes=[];\n    const add=(name,re)=>re.test(all)&&modes.push(name);\n    add('observation',/봤|보았|읽었|들었|확인했|조회|염탐|정체|실제\\s*여부/);\n    add('perception',/인식|추측|어떻게\\s*(?:보|생각)|이미지|평판|평가/);\n    add('thought',/생각|떠올|기억|의식/);\n    add('feeling',/감정|마음|좋아|그리|미련|끌림/);\n    add('action',/행동|움직|다가|실행|답장|연락|선톡|dm|디엠/);\n    add('timing',/언제|시기|타이밍|전조|방아쇠|지연|이번\\s*주|몇\\s*(?:시간|일|주|달)/);\n    add('cause',/왜|이유|원인|병목|계기/);\n    add('compare',/비교|vs|각각|차이|a\\/b|둘\\s*중|두\\s*(?:사람|명|대상)/i);\n    add('choice',/할까\\s*말까|고를|선택|어디가\\s*나|뭐가\\s*나/);\n    add('advice',/조언|대응|뭘\\s*해야|어떻게\\s*해야|행동\\s*기준/);\n    add('outcome',/결과|가능성|될까|올까|성사|합격|흐름/);\n    if(!modes.length)modes.push('general');\n\n    const stage=/(보고\\s*왔|만나고\\s*왔|끝났|이미\\s*(?:했|옴|왔)|연락\\s*(?:왔|옴)|발생\\s*후)/.test(q)?'after'\n      :/(예정|잡혀|앞두|내일\\s*(?:만나|면접)|모레\\s*(?:만나|면접))/.test(q)?'scheduled'\n      :/(들어올|생길|잡힐|아직\\s*(?:없|안)|기회)/.test(q)?'before_opportunity'\n      :'current_or_unspecified';\n    return {version:2,domain,target,modes:[...new Set(modes)].sort(),stage};\n"""
new="""    const modes=[];\n    const add=(name,re)=>re.test(all)&&modes.push(name);\n    const perceptionViewing=/어떻게\\s*(?:봤|보았|보는|볼|보였|느꼈|받아들)/.test(all);\n    if(!perceptionViewing)add('observation',/봤|보았|읽었|들었|확인했|조회|염탐|정체|실제\\s*여부/);\n    add('perception',/인식|추측|어떻게\\s*(?:보|봤|보았|보는|볼|생각|느꼈|받아들)|이미지|평판|평가/);\n    add('thought',/생각|떠올|기억|의식/);\n    add('feeling',/감정|마음|좋아|그리|미련|끌림/);\n    add('action',/행동|움직|다가|실행|답장|연락|선톡|dm|디엠/);\n    add('timing',/언제|시기|타이밍|전조|방아쇠|지연|이번\\s*(?:주|달|개월|분기)|이달|다음\\s*달|다음달|향후\\s*\\d+\\s*(?:일|주|달|개월)|\\d+\\s*개월|몇\\s*(?:시간|일|주|달|개월)/);\n    add('cause',/왜|이유|원인|병목|계기|요인|장애물|장벽|방해|걸림돌|저해|막는|막고/);\n    add('compare',/비교|vs|각각|차이|a\\/b|둘\\s*중|두\\s*(?:사람|명|대상)/i);\n    if(explicitPair&&/(?:중|더|누가|어느|각각|비교|차이|vs)/i.test(all))modes.push('compare');\n    add('choice',/할까\\s*말까|고를|선택|어디가\\s*나|뭐가\\s*나/);\n    add('advice',/조언|대응|뭘\\s*해야|어떻게\\s*해야|행동\\s*기준/);\n    add('outcome',/결과|가능성|될까|올까|성사|합격|흐름|정리(?:되|될|되는)|종결|종료|마무리|귀결|끝(?:날|나는|날지|나게)/);\n    if(!modes.length)modes.push('general');\n\n    const stage=/(보고\\s*왔|만나고\\s*왔|만난\\s*(?:뒤|후)|만남\\s*(?:뒤|후)|관계\\s*(?:뒤|후)|끝났|끝난|이미\\s*(?:했|옴|왔|끝)|지난\\s*만남|그날\\s*(?:뒤|후|이후)|연락\\s*(?:왔|옴)|발생\\s*후)/.test(q)?'after'\n      :/(예정|잡혀|앞두|내일\\s*(?:만나|면접)|모레\\s*(?:만나|면접))/.test(q)?'scheduled'\n      :/(들어올|생길|잡힐|아직\\s*(?:없|안)|기회)/.test(q)?'before_opportunity'\n      :'current_or_unspecified';\n    return {version:3,domain,target,modes:[...new Set(modes)].sort(),stage};\n"""
if old not in s: raise SystemExit('modes/stage block not found')
s=s.replace(old,new,1)

s=s.replace("Number(row.structureProfile.version||0)<2?profile", "Number(row.structureProfile.version||0)<3?profile",1)

p.write_text(s)
print('patched question routing v2')
