-- LUNEA spread-learning release migration
-- Apply only together with the reviewed client release.
-- Current production remains on the pre-release schema until deployment approval.

create or replace function public.prune_spread_learning_memories_per_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  delete from public.spread_learning_memories
  where id in (
    select id
    from public.spread_learning_memories
    where user_id = new.user_id
    order by updated_at desc, id desc
    offset 1000
  );
  return new;
end;
$$;

create table if not exists public.spread_learning_common_candidates (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  structure_key text not null,
  distinct_question_count integer not null default 0 check (distinct_question_count >= 0),
  evidence_hashes text[] not null default '{}',
  auto_check_passed boolean not null default false,
  user_confirmed boolean not null default false,
  pii_scrubbed boolean not null default false,
  status text not null default 'collecting' check (status in ('collecting','eligible','user_confirmed','approved','rejected')),
  anonymized_payload jsonb not null default '{}'::jsonb,
  validation_notes jsonb not null default '{}'::jsonb,
  eligible_at timestamptz,
  confirmed_at timestamptz,
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, structure_key),
  constraint spread_learning_common_candidate_gate check (
    (status not in ('eligible','user_confirmed','approved') or (distinct_question_count >= 3 and auto_check_passed and pii_scrubbed))
    and (status not in ('user_confirmed','approved') or user_confirmed)
  )
);

create index if not exists spread_learning_common_candidates_user_updated_idx
  on public.spread_learning_common_candidates (user_id, updated_at desc);
create index if not exists spread_learning_common_candidates_status_idx
  on public.spread_learning_common_candidates (status, distinct_question_count desc);

alter table public.spread_learning_common_candidates enable row level security;

drop policy if exists "spread learning candidate owners can read" on public.spread_learning_common_candidates;
create policy "spread learning candidate owners can read"
  on public.spread_learning_common_candidates for select
  using ((select auth.uid()) = user_id);

drop policy if exists "spread learning candidate owners can insert" on public.spread_learning_common_candidates;
create policy "spread learning candidate owners can insert"
  on public.spread_learning_common_candidates for insert
  with check ((select auth.uid()) = user_id);

drop policy if exists "spread learning candidate owners can update" on public.spread_learning_common_candidates;
create policy "spread learning candidate owners can update"
  on public.spread_learning_common_candidates for update
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create table if not exists public.spread_learning_common_cases (
  id bigint generated by default as identity primary key,
  structure_key text not null unique,
  anonymized_payload jsonb not null,
  source_candidate_id bigint references public.spread_learning_common_candidates(id) on delete set null,
  validation_meta jsonb not null default '{}'::jsonb,
  status text not null default 'approved' check (status = 'approved'),
  approved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.spread_learning_common_cases enable row level security;

comment on table public.spread_learning_common_candidates is
  'Future common-spread promotion candidates. Collection/validation scaffold only; not consumed by LUNEA automatic spread selection yet.';
comment on table public.spread_learning_common_cases is
  'Approved anonymized common spread cases. Client access intentionally closed until common-case auto-application safeguards are enabled.';
